
# Defines a default set of lint rules enforced for
# projects at Google. For details and rationale,
# see https://github.com/dart-lang/pedantic#enabled-lints.
include: package:flutter_lints/flutter.yaml

linter:
    rules:
      unawaited_futures: true
      omit_local_variable_types: false
      avoid_types_on_closure_parameters: false
      camel_case_types: true
      cancel_subscriptions: true
      comment_references: true
      await_only_futures: true
      exhaustive_cases: true
      avoid_print: false

# For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
# Uncomment to specify additional rules.
# linter:
#   rules:
#     - camel_case_types

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

#   exclude:
#     - path/to/excluded/files/**
